eureka:
  client:
    dashboard:
      enabled: true
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
  instance:
    hostname: localhost
server:
  port: 8010
spring:
  application:
    name: discovery
  profiles: default
